### ISSUE TITLE
mining_ore.lua error in script

### ISSUE THREAD

**Issue by lnxmnky** [Vaevictusnet/Talescripts#129]
Hello,

In line 20 you have zinc as one of the dropdown_ore_values, but there is no corresponding elseif statement in the getPoints function.

I added a new entry at line 157, under tungsten

elseif (dropdown_ore_cur_value == 14) then
  ore = "Zinc";
  stonecount = 10;

This fixed the issue, and allowed the script to work  correctly for zinc

**Comment by Cegaiel** [comment]
Thank  you very much. I'm sorry for the very long delay in seeing this message.  I will merge this on Automato right now!
